//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sm_AntecedentePaciente
    {
        public int idAntecedentePaciente { get; set; }
        public int idAntecedente { get; set; }
        public int idPaciente { get; set; }
        public Nullable<int> idEstado { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public string createdBy { get; set; }
        public Nullable<System.DateTime> updatedDate { get; set; }
        public string updatedBy { get; set; }
    
        public virtual sm_Antecedente sm_Antecedente { get; set; }
    }
}
