//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sm_DatosTipoCalificacion
    {
        public int idDatos { get; set; }
        public int idTipoCalificacion { get; set; }
        public string sexo { get; set; }
        public Nullable<int> edad { get; set; }
        public Nullable<decimal> colesterolTotal { get; set; }
        public Nullable<decimal> colesterolHDL { get; set; }
        public Nullable<decimal> presionSistolica { get; set; }
        public Nullable<bool> esFumador { get; set; }
        public Nullable<bool> diabetes { get; set; }
        public Nullable<decimal> peso { get; set; }
        public Nullable<decimal> talla { get; set; }
        public Nullable<decimal> creatininaSerica { get; set; }
        public Nullable<int> idEstado { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public string createdBy { get; set; }
        public Nullable<System.DateTime> updatedDate { get; set; }
        public string updatedBy { get; set; }
    
        public virtual sm_TipoCalificacion sm_TipoCalificacion { get; set; }
    }
}
