//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sm_GuiaPaciente
    {
        public int idGuiaPaciente { get; set; }
        public int idTipoIdentificacion { get; set; }
        public string numeroIdentificacion { get; set; }
        public int idGuia { get; set; }
        public string observaciones { get; set; }
        public Nullable<int> idEstado { get; set; }
        public Nullable<int> idOrigen { get; set; }
        public Nullable<int> tipoEvento { get; set; }
        public System.DateTime createdDate { get; set; }
        public string createdBy { get; set; }
        public Nullable<System.DateTime> updatedDate { get; set; }
        public string updatedBy { get; set; }
        public string txt1 { get; set; }
        public string txt2 { get; set; }
        public string txt3 { get; set; }
        public string txt4 { get; set; }
        public string txt5 { get; set; }
        public Nullable<decimal> valor1 { get; set; }
        public Nullable<decimal> valor2 { get; set; }
        public Nullable<decimal> valor3 { get; set; }
        public Nullable<decimal> valor4 { get; set; }
        public Nullable<decimal> valor5 { get; set; }
        public string unidad1 { get; set; }
        public string unidad2 { get; set; }
        public string unidad3 { get; set; }
        public string unidad4 { get; set; }
        public string unidad5 { get; set; }
        public Nullable<System.DateTime> fechaEvento { get; set; }
        public Nullable<System.DateTime> fecha1 { get; set; }
        public Nullable<System.DateTime> fecha2 { get; set; }
        public Nullable<System.DateTime> fecha3 { get; set; }
        public Nullable<System.DateTime> fecha4 { get; set; }
        public Nullable<System.DateTime> fecha5 { get; set; }
    
        public virtual sm_Guia sm_Guia { get; set; }
        public virtual sm_OrigenToma sm_OrigenToma { get; set; }
        public virtual sm_Persona sm_Persona { get; set; }
        public virtual sm_TipoEvento sm_TipoEvento { get; set; }
    }
}
