//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sm_Guia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sm_Guia()
        {
            this.sm_GuiaPaciente = new HashSet<sm_GuiaPaciente>();
        }
    
        public int idGuia { get; set; }
        public int idTipoGuia { get; set; }
        public string idCodigoTipo { get; set; }
        public string descripcion { get; set; }
        public string version { get; set; }
        public int idPrograma { get; set; }
        public int idRiesgo { get; set; }
        public Nullable<int> cantidadRiesgo { get; set; }
        public System.DateTime createdDate { get; set; }
        public string createdBy { get; set; }
        public Nullable<System.DateTime> updatedDate { get; set; }
        public string updatedBy { get; set; }
        public Nullable<int> idEstado { get; set; }
        public Nullable<int> peso { get; set; }
        public string ce_titulo { get; set; }
        public string ce_url { get; set; }
        public Nullable<int> ce_estadoDoc { get; set; }
        public Nullable<System.DateTime> ce_fechaRegistro { get; set; }
        public Nullable<decimal> po_act { get; set; }
        public Nullable<decimal> po_grupoAct { get; set; }
    
        public virtual sm_Estado sm_Estado { get; set; }
        public virtual sm_Riesgo sm_Riesgo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sm_GuiaPaciente> sm_GuiaPaciente { get; set; }
        public virtual sm_Programa sm_Programa { get; set; }
        public virtual sm_TipoGuia sm_TipoGuia { get; set; }
    }
}
