//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sm_LimitesExamen
    {
        public int idRegistro { get; set; }
        public string codigoCups { get; set; }
        public string descripción { get; set; }
        public int idGenero { get; set; }
        public int edadInferior { get; set; }
        public int edadSuperior { get; set; }
        public int idFormatoEdad { get; set; }
        public string descAnalisis { get; set; }
        public decimal valorInferior { get; set; }
        public decimal valorSuperior { get; set; }
        public int idSemaforo { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual sm_FormatoEdad sm_FormatoEdad { get; set; }
        public virtual sm_Genero sm_Genero { get; set; }
        public virtual sm_Semaforo sm_Semaforo { get; set; }
    }
}
