//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sm_LogNotificaciones
    {
        public int id { get; set; }
        public int idGuiaPaciente { get; set; }
        public string idNotificacion { get; set; }
        public string fechaProgramada { get; set; }
        public string token { get; set; }
    }
}
