//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sm_NotificacionesPush
    {
        public int idPush { get; set; }
        public int idTipoIdentificacion { get; set; }
        public string numeroIdentificacion { get; set; }
        public string titulo { get; set; }
        public string mensaje { get; set; }
        public bool enviado { get; set; }
        public string token { get; set; }
        public System.DateTime fechaCreacion { get; set; }
        public Nullable<System.DateTime> fechaEnvio { get; set; }
        public Nullable<int> idPeriodicidad { get; set; }
        public Nullable<System.DateTime> fechaInicio { get; set; }
        public Nullable<System.DateTime> fechaFin { get; set; }
        public Nullable<int> cantidadTomas { get; set; }
        public string horaInicio { get; set; }
        public Nullable<int> idGuiaPaciente { get; set; }
        public Nullable<int> idEstado { get; set; }
    }
}
