//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sm_Notificacion
    {
        public int idNotificacion { get; set; }
        public Nullable<int> idGuia { get; set; }
        public Nullable<int> idUsuario_Solicita { get; set; }
        public Nullable<int> idUsuario_Envia { get; set; }
        public Nullable<int> idUsuario_Destino { get; set; }
        public string asunto { get; set; }
        public Nullable<System.DateTime> fecha_Respuesta { get; set; }
        public Nullable<bool> Resuelto { get; set; }
        public Nullable<bool> Leido { get; set; }
        public string idTipoNotificacion { get; set; }
        public string detalle { get; set; }
        public string idEstado { get; set; }
        public Nullable<System.DateTime> FechaCierre { get; set; }
        public Nullable<int> enviado { get; set; }
    }
}
