//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sm_Opcion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sm_Opcion()
        {
            this.sm_RolOpcion = new HashSet<sm_RolOpcion>();
        }
    
        public int IdOpcion { get; set; }
        public string NombreOpcion { get; set; }
        public string URL { get; set; }
        public int Orden { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> IdOpcionPadre { get; set; }
        public Nullable<bool> Activa { get; set; }
        public string URLImagen { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sm_RolOpcion> sm_RolOpcion { get; set; }
    }
}
