//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sm_ParametroReglas
    {
        public int idParametroReglas { get; set; }
        public Nullable<int> idReglas { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> idEstado { get; set; }
    }
}
