//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sm_Parametro
    {
        public int idParametro { get; set; }
        public string modulo { get; set; }
        public string descripcion { get; set; }
        public string valor { get; set; }
        public string nombreParametro { get; set; }
    }
}
