//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sm_ParametrosCargue
    {
        public int idRegistro { get; set; }
        public System.DateTime FechaCargue { get; set; }
        public string Periodo { get; set; }
    }
}
