//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sm_PacientePrograma
    {
        public int idTipoIdentificacion { get; set; }
        public string numeroIdentificacion { get; set; }
        public int idPrograma { get; set; }
        public int idEstado { get; set; }
        public string observaciones { get; set; }
        public System.DateTime createdDate { get; set; }
        public string createdBy { get; set; }
        public Nullable<System.DateTime> updatedDate { get; set; }
        public string updatedBy { get; set; }
    
        public virtual sm_Persona sm_Persona { get; set; }
        public virtual sm_Programa sm_Programa { get; set; }
    }
}
