//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sm_Paciente
    {
        public int idTipoIdentificacion { get; set; }
        public string numeroIdentificacion { get; set; }
        public string segmento { get; set; }
        public string planMp { get; set; }
        public string tipoContrato { get; set; }
        public string nombreColectivo { get; set; }
        public Nullable<int> institucion { get; set; }
        public int idTipoIdentificacionMedico { get; set; }
        public string numeroIdentificacionMedico { get; set; }
        public Nullable<int> recibeNotParentesco { get; set; }
        public string nombresParantesco { get; set; }
        public Nullable<int> idParentesco { get; set; }
        public string celularParentesco { get; set; }
        public string telefonoFijoParentesco { get; set; }
        public string correoParentesco { get; set; }
        public Nullable<int> idTipoIngreso { get; set; }
        public Nullable<int> idMedioAtencion { get; set; }
        public Nullable<System.DateTime> fechaRegistro { get; set; }
        public int riesgo { get; set; }
        public int idEstado { get; set; }
        public Nullable<bool> esMonitoreado { get; set; }
        public System.DateTime createdDate { get; set; }
        public string createdBy { get; set; }
        public string updatedBy { get; set; }
        public Nullable<System.DateTime> updatedDate { get; set; }
    
        public virtual sm_CentroSalud sm_CentroSalud { get; set; }
        public virtual sm_MedioAtencion sm_MedioAtencion { get; set; }
        public virtual sm_Parentesco sm_Parentesco { get; set; }
        public virtual sm_Persona sm_Persona { get; set; }
        public virtual sm_Persona sm_Persona1 { get; set; }
        public virtual sm_Riesgo sm_Riesgo { get; set; }
        public virtual sm_TipoIngreso sm_TipoIngreso { get; set; }
    }
}
