//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sm_RolOpcion
    {
        public int idRol { get; set; }
        public int idOpcion { get; set; }
        public Nullable<bool> crear { get; set; }
        public Nullable<bool> leer { get; set; }
        public Nullable<bool> actualizar { get; set; }
        public Nullable<bool> eliminar { get; set; }
        public string createdBy { get; set; }
        public System.DateTime createdDate { get; set; }
        public string updatedBy { get; set; }
        public Nullable<System.DateTime> updatedDate { get; set; }
    
        public virtual sm_Opcion sm_Opcion { get; set; }
        public virtual sm_Rol sm_Rol { get; set; }
    }
}
