//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sm_TipoGuiaXPrograma
    {
        public int idPrograma { get; set; }
        public int idTipoGuia { get; set; }
        public Nullable<bool> esPonderadoPorGrupo { get; set; }
        public Nullable<decimal> ponderadorGrupo { get; set; }
    
        public virtual sm_Programa sm_Programa { get; set; }
        public virtual sm_TipoGuia sm_TipoGuia { get; set; }
    }
}
