//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sm_TipoGuia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sm_TipoGuia()
        {
            this.sm_Guia = new HashSet<sm_Guia>();
            this.sm_TipoGuiaXPrograma = new HashSet<sm_TipoGuiaXPrograma>();
        }
    
        public int idTipoGuia { get; set; }
        public string descripcion { get; set; }
        public int idEstado { get; set; }
        public string version { get; set; }
        public System.DateTime createdDate { get; set; }
        public string createdBy { get; set; }
        public Nullable<System.DateTime> updatedDate { get; set; }
        public string updatedBy { get; set; }
        public Nullable<bool> esPonderadoPorGrupo { get; set; }
        public Nullable<decimal> ponderadorGrupo { get; set; }
    
        public virtual sm_Estado sm_Estado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sm_Guia> sm_Guia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sm_TipoGuiaXPrograma> sm_TipoGuiaXPrograma { get; set; }
    }
}
