//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sm_Usuario
    {
        public int idUsuario { get; set; }
        public Nullable<int> idTipoIdentificacion { get; set; }
        public string numeroIdentificacion { get; set; }
        public string usuario { get; set; }
        public string contrasena { get; set; }
        public bool estado { get; set; }
        public Nullable<int> intentos { get; set; }
        public Nullable<int> idEmpresa { get; set; }
        public string createdBy { get; set; }
        public System.DateTime createdDate { get; set; }
        public string updatedBy { get; set; }
        public Nullable<System.DateTime> updatedDate { get; set; }
    }
}
